### ISSUE TITLE
Make sure tables can be pasted into the editor

### ISSUE THREAD

**Issue by ericras** [unlcms/project-herbie#100]

**Comment by macburgee1** [comment]
[forcePasteAsPlainText](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-forcePasteAsPlainText) will prevent pasting tables. We'll want to replace it with [pasteFilter](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter) instead.

**Comment by ericras** [comment]
I think we should be good in CKEditor5 with this.

#378 addresses adding the dcf-table class so they look good.
