### ISSUE TITLE
Need a global (all sites in multisite) settings file that can be configured per environment?

### ISSUE THREAD

**Issue by ericras** [unlcms/project-herbie#152]
Purpose: Have a file to put settings that apply to all sites, is per-environment, and is not committed to the repo.

Example: Drush needs a lot of memory to do a site install. We need to be able to set something like `ini_set('memory_limit', '512M');` on a specific environment.

Current settings files and why they aren't suitable:

- profiles/herbie/includes/settings.php.inc is global but its contents are committed to the repo.  Maybe that is ok for some things (#153)? Not for secrets though.
- sites/default/settings.php and sites/default/default.settings.php would be suitable but can't be modified because it is re-built every time core is updated.

**Comment by macburgee1** [comment]
Are secrets the dealbreaker for using profiles/herbie/includes/settings.php.inc? That file already handles different environments. I think we benefit from having config by environment under version control.

For secrets, we could use the [Key](https://www.drupal.org/project/key) module. On a recent project, I used Key to store an API key outside the web root for a custom Eventbrite integration module.

**Comment by ericras** [comment]
sites/all/settings.php.sample file added in 8d250cec16c24d823d10a1e6f9b31e4a6e0adbfd
