### ISSUE TITLE
Install ImageMagick module

### ISSUE THREAD

**Issue by macburgee1** [unlcms/project-herbie#22]
https://www.drupal.org/project/imagemagick

version 8.x-2.4 instead of 8.x-1.0-alpha

**Comment by macburgee1** [comment]
Referenced config from unlcms/UNL-CMS-2. I left 'path_to_binaries' empty, and it runs fine in Lando. Unless there's a reason on production to set the path, I think we're good here. @ericras thoughts?

**Comment by ericras** [comment]
Should be ok without the path.  Running `convert` works on the production server.

**Comment by ericras** [comment]
On my machine without the path I get "sh: convert: command not found" even though `convert` exists

**Comment by ericras** [comment]
Looks like to run this on a mac you need the path set

https://stat.ethz.ch/pipermail/r-sig-mac/2014-October/011144.html

``
It is, because Yosemite ignores PATH for processes started from a GUI application. You will see if you run
system("echo $PATH")

You have to use full paths in Yosemite for anything that is not on the "sanctioned" PATH -- or use R from the shell.
```

**Comment by macburgee1** [comment]
That's a good catch. Because the path may differ from dev machine to dev machine, we'll probably want to use `$config['imagemagick.settings']['path_to_binaries'] = "path/to/binaries";` locally in settings.php.

**Comment by macburgee1** [comment]
@ericras - Does the solution above work? Can we close this issue?

**Comment by ericras** [comment]
We probably need development/local settings set up and this referenced in the README

**Comment by macburgee1** [comment]
That sounds like a good idea. Anything that is global for the development environment should probably go in web/profiles/herbie/includes/settings.php.inc. Configuration that may differ from development environment to development environment would be suitable for settings.local.php. The path to ImageMagick binaries would seem to fit in the latter category.
