### ISSUE TITLE
Allow custom sized inline images

### ISSUE THREAD

**Issue by macburgee1** [unlcms/project-herbie#283]
Currently, there are two responsive image styles available for inline images: Narrow (50%) and Wide (100%). There are uses cases where these two responsive images styles will be in adequate. Logos are a good example. It may simply be the case where an editor needs to include a 300px x 75px logo. Neither the Narrow or Wide responsive image styles would work well in this case. We need to figure out a way to support one-off images for responsive images.

**Comment by ericras** [comment]
"Original"/"Default" image has been added as a chose-able media view mode.
