### ISSUE TITLE
Create Features Read-Only module

### ISSUE THREAD

**Issue by ericras** [unlcms/project-herbie#319]
Config that is under control of a feature needs to be read only.  Look to https://www.drupal.org/project/config_readonly for ideas.

**Comment by crayruris** [comment]
This should be able to be plopped into any sized grid component
			<div class="dcf-col-100% dcf-grid-thirds@md dcf-col-gap-6 dcf-row-gap-3 dcf-p-6 unl-bg-scarlet">
				<div class="dcf-d-flex dcf-ai-center dcf-jc-center">
					<h2 class="dcf-mb-0 dcf-uppercase unl-cream"><span class="unl-font-display">Create Your Path</span></h2>
				</div>
				<div class="dcf-d-flex dcf-ai-center dcf-jc-center dcf-pt-2 dcf-pb-2">
					<p class="dcf-mb-0 unl-cream dcf-txt-center">Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.</p>
				</div>
				<div class="dcf-d-flex dcf-ai-center dcf-jc-center dcf-pt-2 dcf-pb-2">
					<a class="dcf-btn dcf-btn-inverse-primary dcf-uppercase" href="https://uiowa.edu/">Request Information</a>
				</div>
			</div>

**Comment by ericras** [comment]
https://github.com/unlcms/features_readonly

**Comment by ericras** [comment]
There are limitations to this approach. It is difficult to account for Third Party Settings (like creating field groups on content types).  It might be better for us to consider a custom approach of just blocking off paths like `/admin/structure/types/manage/builder_page/*`
