### ISSUE TITLE
Add text width styles to standard text format 

### ISSUE THREAD

**Issue by sarongebre** [unlcms/project-herbie#427]
Add text width styles to standard text format 

dcf-w-max-md 
dcf-w-max-lg
dcf-w-max-xl

**Comment by ericras** [comment]
Thinking more about this: if we add them as styles in ckeditor like the current PR #467 , they're only available to be put on <p> tags.  Sure, we could also add them as styles for headings but then you have to put the style on each element.

Maybe what we actually want is to make these Layout Builder Styles on the Text Area block?


<img width="1574" alt="Screenshot 2023-06-30 at 10 59 16 AM" src="https://github.com/unlcms/project-herbie/assets/446357/6b7ad9fc-5bda-4297-ab38-69a8d3da4f22">
