### ISSUE TITLE
Form Field Width not Responsive

### ISSUE THREAD

**Issue by sarongebre** [unlcms/project-herbie#455]
![image](https://github.com/unlcms/project-herbie/assets/72580736/9d01bef9-cfa5-4d2b-b306-791cfa8200aa)

**Comment by ericras** [comment]
Input fields have size="60" on them.  we probably need max-width: 100%; added either in the CMS or in DCF

**Comment by ericras** [comment]
7cfe984ac5a130df2b2d0d36c841d2f319ad4112
