### ISSUE TITLE
Seeing Duplicate Images in Media Library

### ISSUE THREAD

**Issue by mhonke** [unlcms/project-herbie#552]
https://sirius.unl.edu/admin/content/media/

<img width="1170" alt="Screenshot 2023-09-20 at 10 37 53 AM" src="https://github.com/unlcms/project-herbie/assets/84044289/59d89985-fb67-4a35-b8c1-fc834219e108">

**Comment by sarongebre** [comment]
Hi Matt, I looked into this and just wanted to let you know that the images aren't getting duplicated in this instance. It's just that every time a node that has an image is updated, the table media view stores that information and displays it on that table view for each update. If you go to the Grid media view, you shouldn't see those images. The Grid video doesn't document the number of updates.
 
<img width="323" alt="image" src="https://github.com/unlcms/project-herbie/assets/72580736/a8dc55e2-8412-4547-a0db-c9a3637a13a9">

**Comment by mhonke** [comment]
Saron,
Thanks for the response,

When I go to “Grid” view, I receive an Access denied message.

Matt

From: Saron Solomon Gebre ***@***.***>
Date: Wednesday, December 13, 2023 at 9:21 AM
To: unlcms/project-herbie ***@***.***>
Cc: Matthew Honke ***@***.***>, Author ***@***.***>
Subject: Re: [unlcms/project-herbie] Seeing Duplicate Images in Media Library (Issue #552)
Non-NU Email
________________________________

Hi Matt, I looked into this and just wanted to let you know that the images aren't getting duplicated in this instance. It's just that every time a node that has an image is updated, the table media view stores that information and displays it on that table view for each update. If you go to the Grid media view, you shouldn't see those images. The Grid video doesn't document the number of updates.
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/unlcms/project-herbie/assets/72580736/a8dc55e2-8412-4547-a0db-c9a3637a13a9__;!!PvXuogZ4sRB2p-tU!E-uiFazqFIDz5A6egZzSY3xoQDBEXJePCoL1mH5InHNyPy-DKu0rszP5qLmlKBVrk4VyBH7_gjrm3d9Cx2vri2LzZQ$>
