### ISSUE TITLE
 D10 template issues (Schema.org and HTML tags)

### ISSUE THREAD

**Issue by sarongebre** [unlcms/project-herbie#604]
Error message - “itemprop” attribute was specified, but the element is not a property of any item."

`<span itemprop="streetAddress">
`

**Comment by tommyneu** [comment]
The footer is also being set up incorrectly with the phone number link missing an closing tag and description details (`dd`) coming before the description term (`dt`) for the social media.

**Comment by tommyneu** [comment]
These footer issues are making every D10 site fail webaudit checks and causing their scores to go to 0
