### ISSUE TITLE
File Upload limitations / path strategy

### ISSUE THREAD

**Issue by macburgee1** [unlcms/project-herbie#62]
## File Upload limitations
What file upload limitations do we want to implement for File media files and Image media files?

- Max file size
- Allowed formats
- Min/max resolution (images only)

I think we should have some max file size. I also think we should have a max resolution. I've used 5000x5000px in the past on projects. If there are too many pixels, that can cause the server to choke.

The default allowed formats are as follows:
- File
-- txt, doc, docx, pdf
- Image
-- png, gif, jpg, jpeg

## Path strategy
The default path uses tokens and is `[date:custom:Y]-[date:custom:m]`. Since these files are managed, it's not critical that we namespace them; avoiding collisions is more important. That said, I think we should use `public: //media/file/[namespace collision avoidance strategy]` and `public: //media/image/[namespace collision avoidance strategy]`, respectively. Core uses `[date:custom:Y]-[date:custom:m]` to avoid filename collisions. I'd like to discuss this with the team.

**Comment by macburgee1** [comment]
Allowed files mirrors what we used for Webform.
Documents: txt rtf pdf doc docx odt ppt pptx odp xls xlsx ods
Images: gif jpg jpeg png
Max upload is 40 MB.
Max resolution is 5000x5000px.

We still need a path strategy.

**Comment by macburgee1** [comment]
Core uses `[date:custom:Y]-[date:custom:m]` in uploaded file paths to avoid namespace collisions. This will be problematic because we're allowing users to deep link to files. Here's an example: Last week a user uploaded a document, academic-standards-policy.pdf, which was uploaded to /sites/default/files/**2019-06**/academic-standards-policy.pdf. On Monday, her office discovered an error in the document and uploaded a replacement; however, it was uploaded to /sites/default/files/**2019-07**/academic-standards-policy.pdf. The first link was already e-mailed out and now the user can no way of replacing the existing document. (File replacement will be possible with #89.)

**Comment by ericras** [comment]
Media Entity File Replace solves the problem cited in the last comment.
