### ISSUE TITLE
Rename layout builder "sections" to "bands"

### ISSUE THREAD

**Issue by macburgee1** [unlcms/project-herbie#63]
Layout builder uses the term "sections", and we use the term "bands". This issue proposes using the [String Overrides](https://www.drupal.org/project/stringoverrides) module to modify the UI to replace references to "sections" with references to "bands".

D8 ships with an Interface Translation module that builds on the multi-lingual capabilities of D8 core. That said, I think this is overkill for what we need. String Overrides tests successfully in D8 for me. That said, there is no D8 release, and it's been unsupported for a long time with no commits in about 13 months. We'd want to secure maintainership.

![Screen Shot 2019-05-02 at 3 05 51 PM](https://user-images.githubusercontent.com/1521132/57103617-f1b81c00-6ceb-11e9-8cf4-dfbda9fe2c11.png)

**Comment by ericras** [comment]
I think we've determined that we're going to stick with 'sections'.  People have never been satisfied with calling them 'bands' anyway.
