### ISSUE TITLE
Ajax error ajax.$form.ajaxSubmit() is not a function

### ISSUE THREAD

**Issue by sarongebre** [unlcms/project-herbie#696]
This error first showed up in one of our training videos when Aaron tried to save a page after editing a layout builder section. 
<img width="481" alt="image" src="https://github.com/unlcms/project-herbie/assets/72580736/7ce5a9b3-89e9-4091-87c8-89ebb602b337">

There seems to be a patch that may resolve this issue - https://www.drupal.org/files/issues/2023-08-07/drupal-ajax-error-2755791-18_0.patch

**Comment by ericras** [comment]
`I'm getting reports about an error message that shows up on forms with multiple pages. For example, this form: https://libraries.unl.edu/community-card-registration-form/ When you click on the check box and then hit the Next button, we get a message that reads: "An error occurred while attempting to process /community-card-registration-form/?ajax_form=1&_wrapper_format=drupal_ajax: ajax.$form.ajaxSubmit is not a function"`

**Comment by ericras** [comment]
https://www.drupal.org/project/drupal/issues/2755791
