### ISSUE TITLE
Can't add specific media hub remote video Gives error.  https://mediahub.unl.edu/media/8412

### ISSUE THREAD

**Issue by dmerriman2** [unlcms/project-herbie#768]
The website encountered an unexpected error. Please try again later.

Drupal\Core\Entity\EntityStorageException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'm_rv_html_representation_value' at row 1: INSERT INTO "media__m_rv_html_representation" ("entity_id", "revision_id", "bundle", "delta", "langcode", "m_rv_html_representation_value") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5); Array ( [:db_insert_placeholder_0] => 350 [:db_insert_placeholder_1] => 350 [:db_insert_placeholder_2] => remote_video [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => <iframe src="https://mediahub.unl.edu/media/8412?format=iframe&autoplay=0" title="Video Player: Supporting Children&#039;s Self-Regulation in Eating: Understanding Children&#039;s Ability to Self-Regulate Food Intake" allowfullscreen frameborder="0"></iframe> ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 815 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by sarongebre** [comment]
Hi @dmerriman2, thanks for reporting. How are you going about adding the Mediahub remote video? Thanks.

**Comment by dmerriman2** [comment]
Media->Add Media->Remote Video, Past URL, Save, Error.

Have also tried within a text area or simple media component.

No other videos have had any issues, just this particular one.

[https://ucomm.unl.edu/images/email-signature/Nebraska_N_RGB_small_on_white.gif]
David Merriman
Web Developer
University of Nebraska–Lincoln
College of Education & Human Sciences
4024131531<tel:4024131531>

**Comment by dmerriman2** [comment]
Same issue with the follow vids...  name too long?
https://mediahub.unl.edu/media/9819
https://mediahub.unl.edu/media/9820
https://mediahub.unl.edu/media/9821

**Comment by sarongebre** [comment]
> Same issue with the follow vids... name too long? https://mediahub.unl.edu/media/9819 https://mediahub.unl.edu/media/9820 https://mediahub.unl.edu/media/9821

I am not sure. Maybe? I haven't gotten a chance to look into this issue yet. I will do that as soon as I finish some tasks I am currently working on.

**Comment by sarongebre** [comment]
@dmerriman2 This issue should be resolved by pull request #[786](https://github.com/unlcms/project-herbie/pull/786). I also noticed a problem when adding a remote media hub video and trying to center it with the narrow view mode. That issue should be fixed as well.

This hasn't been pushed to the production servers yet as it hasn’t gone through the deployment process. In the meantime, if you need the remote videos to work urgently, you could reduce the title length to fewer than 100 characters.
