### ISSUE TITLE
Hero image `source` is missing `em` unit in the media query

### ISSUE THREAD

**Issue by skoolbus39** [unlcms/project-herbie#771]
The `media` attribute for the hero image `source` has a value that is missing the `em` unit. Here is the current code:

```
<source srcset="/sites/unl.edu.business-and-finance.sustainability/files/styles/16_9_2129x1198/public/media/image/about-hero.png?itok=0h4GbjyY 1x, /sites/unl.edu.business-and-finance.sustainability/files/styles/16_9_3192x1796/public/media/image/about-hero.png?itok=zxnDFAZu 1.5x, /sites/unl.edu.business-and-finance.sustainability/files/styles/16_9_4258x2395/public/media/image/about-hero.png?itok=_kxkl7Sm 2x" media="all and (min-width: 99.78)" type="image/png"/>
```
Instead, it should be `media="all and (min-width: 99.78em)"`.

[Here](https://webaudit.unl.edu/sites/108/pages/17444195/marks/413578621/) is an example of the error on WebAudit.

**Comment by sarongebre** [comment]
This issue was addressed in [issue #689](https://github.com/unlcms/project-herbie/issues/689). The site wasn't reflecting the changes due to caching issues. I cleared the cache, which resolved the syncing problem.
