### ISSUE TITLE
Person Content Type: Add Link to profile if Photo is clicked

### ISSUE THREAD

**Issue by crayruris** [unlcms/project-herbie#845]
Currently the Photo has a zoom animation on it if moused over but doesn't do anything when clicked. Multiple folk have asked if clicking the photo can take them to the full profile.

**Comment by ericras** [comment]
Are you referencing the teaser view?  When a teaser photo is clicked, go to the full Person page?

**Comment by crayruris** [comment]
None of the Teaser options have this functionality. I was wanting it on Featured and Small specifically

**Comment by ericras** [comment]
- on the person name link add the dcf-card-link class
- on the person's <div> add dcf-card-as-link class
- add this javascript block on the page:

<script>
  window.addEventListener('inlineJSReady', function() {
    WDN.initializePlugin('card-as-link');
  });
</script>
