### ISSUE TITLE
Protected Pages Module Issues

### ISSUE THREAD

**Issue by beckyaiken** [unlcms/project-herbie#873]
- **Can't set global password.** You select the global password setting, but when you go to add individual protected pages, it won't let you save unless you enter a password for the page.
- **Can't set individual pages password.** Lets you save, but doesn't ask you for password, even when viewing page in an incognito window. When you edit the protected page settings again, the password is gone. I thought maybe it was because the password was weak, but it didn't work with a strong password either.

**Comment by beckyaiken** [comment]
Site: https://cms.unl.edu/ianr/food-science/farrp/admin/config/system/protected_pages/

**Comment by sarongebre** [comment]
Removing the trailing slash from the path for the protected pages resolved the issue.
