### ISSUE TITLE
Uploaded File replacement functionality (in File & Media fields)

### ISSUE THREAD

**Issue by macburgee1** [unlcms/project-herbie#89]
Here's a core issue: https://www.drupal.org/project/drupal/issues/2648816. There's been nothing meaningful happening there - no patches have been offered since the issue was opened in Jan 2016.

This module will take advantage of a proposed hook_file_upload() function: https://www.drupal.org/project/drupal/issues/3065698.

**Comment by macburgee1** [comment]
Let's take a look at the new [Media Entity File Replace](https://www.drupal.org/project/media_entity_file_replace) module. It sidesteps a number of issues I was running into.

In my initial testing, it works as I expected. Because it can only act on the edit form (and not on the add form), it shouldn't be possible to overwrite a file accidentally (e.g. file with same name already exists on another media entity.)

We'll need to figure out the external cache piece, however.

**Comment by macburgee1** [comment]
See code example from https://www.drupal.org/project/acquia_purge/issues/2911828#comment-12450381:

```
/**
 * Implements hook_entity_update().
 */
function my_module_entity_update(EntityInterface $entity) {
  $type = $entity->getEntityTypeId();
  if ($type != 'file') {
    return;
  }

  $purgeInvalidationFactory = \Drupal::service('purge.invalidation.factory');
  $purgeQueuers = \Drupal::service('purge.queuers');
  $purgeQueue = \Drupal::service('purge.queue');

  $queuer = $purgeQueuers->get('coretags');
  // Invalidate cache tags so all pages that have the file get banned from varnish
  // Also invalidate the file's url.
  $invalidations = [
    $purgeInvalidationFactory->get('tag', 'file:' . $entity->id()),
    $purgeInvalidationFactory->get('url', file_create_url($entity->getFileUri())),
  ];

  $purgeQueue->add($queuer, $invalidations);
}
```
It would be nice if the Media Entity File Replace module provided a hook for us to use as a trigger. That said, in `media_entity_file_replace_entity_extra_field_info()`, they check if `$mediaType->getSource() instanceof File`. If we can access that information from `$entity`, that would be a reasonable solution.

**Comment by ericras** [comment]
Media Entity File Replace added: 73fedef052ec92e0a20069ea1f9023e8a020b1d3
